; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[platformio]
; default_envs = esp32-s3-n16r8

[env]
lib_deps = 
	tzapu/WiFiManager@^2.0.17
	adafruit/RTClib@^2.1.4
	adafruit/Adafruit AHTX0@^2.0.5
	adafruit/Adafruit BMP280 Library@^2.6.8
	fastled/FastLED@^3.9.4
	mathertel/LiquidCrystal_PCF8574@^2.2.0
	knolleary/PubSubClient@^2.8
	adafruit/Adafruit GFX Library@^1.11.11
	adafruit/Adafruit SSD1306@^2.5.13

[env:esp32]
platform = espressif32
board = esp32dev
framework = arduino
monitor_speed = 115200
upload_speed = 921600
; upload_port = /dev/cu.wchusbserial57460013071
; monitor_port = /dev/cu.wchusbserial57460013071
build_flags = -Duseesp32

[env:esp32-s3-n16r8]
platform = espressif32
board = esp32-s3-devkitm-1
framework = arduino
debug_tool = esp-builtin
monitor_speed = 115200
; monitor_dtr = 0
; monitor_rts = 0
; monitor_port = /dev/cu.wchusbserial58FA0779861
; upload_port = /dev/cu.wchusbserial58FA0779861
; upload_port = /dev/cu.wchusbserial14130
upload_speed = 921600
build_flags = -Duseesp32s3
board_build.arduino.memory_type = qio_opi
board_build.arduino.partitions = default_16MB.csv
board_build.extra_flags = 
	-DBOARD_HAS_PSRAM
board_build.flash_mode = qio
board_build.psram_type = opi
board_upload.flash_size = 16MB
board_upload.maximum_size = 16777216
